baseurl: ""

author:
  name: Timothée JULIEN
title: Bloc-notes
description: Centralisation de mes notes et liens en tout genre.
url: https://bloc-notes.timotheejulien.fr
permalink: /:categories/:year/:month/:day/:title/
timezone: Europe/Paris

collections:
  previews:
    output: true
    permalink: /previews/:slug/

plugins:
  - jekyll-paginate

paginate: 30       # Nombre de posts par page
paginate_path: "/page:num/"  # Le chemin pour les pages paginées