author:
  name: Timothée JULIEN
title: Bloc-notes
description: Centralisation de mes notes et liens en tout genre.
url: https://timotheejulien.github.io/notes/
permalink: /:categories/:year/:month/:day/:title/

collections:
  previews:
    output: true
    permalink: /previews/:slug/