# This workflow deploys a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main  # Change to your main branch name
  workflow_dispatch:  # Allows manual trigger of the workflow

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4  # Ensure Ruby version matches your project
          bundler-cache: true  # Cache installed gems

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build site with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload build output
        uses: actions/upload-pages-artifact@v3  # Upload the _site directory as an artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
