# .github/workflows/deploy-jekyll.yml

name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: ["main"]  # Trigger only on pushes to the main branch
  workflow_dispatch:  # Allows manual trigger from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.3.4'   # Specify Ruby version compatible with your site
          bundler-cache: true   # Enable bundler caching for faster builds

      - name: Install dependencies
        run: |
          gem install bundler  # Ensure Bundler is available
          bundle install        # Install gems from your Gemfile

      - name: Set up GitHub Pages
        id: pages
        uses: actions/configure-pages@v2  # Prepares deployment to GitHub Pages

      - name: Build site with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1  # Uploads the _site directory as an artifact

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
